FROM golang:1.16.15-alpine3.15 AS builder
RUN apk --no-cache add gcc git make bash
RUN git config --global http.version HTTP/1.1
ADD . /go/src/github/csi-snapshotter
WORKDIR /go/src/github/csi-snapshotter
RUN make

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="CSI External Snapshotter Sidecar"

COPY --from=builder /go/src/github/csi-snapshotter/bin/csi-snapshotter csi-snapshotter
ENTRYPOINT ["/csi-snapshotter"]