FROM golang:1.16.15-alpine3.15 AS builder
RUN apk --no-cache add gcc git make bash
RUN git config --global http.version HTTP/1.1
ADD . /go/src/github/snapshot-controller
WORKDIR /go/src/github/snapshot-controller
RUN make

FROM gcr.io/distroless/static:latest
LABEL maintainers="Kubernetes Authors"
LABEL description="Snapshot Controller"

COPY --from=builder /go/src/github/snapshot-controller/bin/snapshot-controller  snapshot-controller
ENTRYPOINT ["/snapshot-controller"]
